##directories and graph build

directories:
  pockets: '~/dataset_graph/data'
  pos_list: '~/dataset_graph/TOUGH-M1/TOUGH-M1_positive.list'
  neg_list: '~/dataset_graph/TOUGH-M1/TOUGH-M1_negative.list'
  cluster_map: '~/graphpocket/cluster_map.pkl'
  result_dir: '~/graphpocket/results'

graph:
  threshold_k: 6
  algorithm: 'bruteforce-blas'

##model config

model:
  input_scalar_size: 24
  output_scalar_size: 64
  edge_feat_size: 1
  vector_size: 16
  n_message_gvps: 1
  n_update_gvps: 1
  n_convs: 2
  dropout: 0.25
  message_norm: 24
  vector_gating: true
  xavier_init: true

loss:
  margin: 1.2

##train config and hyperparameters

train:
  n_epochs: 100
  batch_size: 64
  n_workers: 6

  optimizer:
    type: 'Adam'
    lr: 0.05
    weight_decay: 0.00001
  
  scheduler:
    type: "StepLR"
    params:
      step_size: 20
      gamma: 0.1
      
#wandb sweep args: dropout, margin, lr, weight_decay, step_size, gamma, n_convs
