program: graphpocket/gnn/train.py
name: sweep1-bayes
project: graphpocket
method: bayes
metric:
  goal: maximize
  name: AUC of ROC Curve
parameters:
  step_size:
    max: 30
    min: 15
    distribution: int_uniform
  gamma:
    max: 0.75
    min: 0.1
    distribution: uniform
  type:
    values:
      - StepLR
    distribution: categorical
  weight_decay:
    max: 0.0001
    min: 1e-7
    distribution: uniform
  type:
    values:
      - Adam
    distribution: categorical
  lr:
    max: 0.01
    min: 0.00001
    distribution: uniform
  n_epochs:
    max: 100
    min: 25
    distribution: int_uniform


  output_scalar_size:
    max: 128
    min: 64
    distribution: int_uniform
  input_scalar_size:
    max: 8
    min: 2
    distribution: int_uniform
  vector_gating:
    values:
      - "true"
      - "false"
    distribution: categorical
  xavier_init:
    values:
      - "true"
      - "false"
    distribution: categorical
  vector_size:
    max: 32
    min: 8
    distribution: int_uniform
  n_convs:
    max: 8
    min: 2
    distribution: int_uniform
  dropout:
    max: 0.5
    min: 0.05
    distribution: uniform
  margin:
    max: 1.5
    min: 0.75
    distribution: uniform
  threshold_k:
    max: 12
    min: 3
    distribution: int_uniform
  algorithm:
    values:
      - bruteforce-blas
      - kd-tree
    distribution: categorical

early_terminate:
  type: hyperband
  eta: 3
  min_iter: 5
