##directories and graph build

directories:
  pockets: '~/dataset_graph/data'
  pos_list: '~/dataset_graph/TOUGH-M1/TOUGH-M1_positive.list'
  neg_list: '~/dataset_graph/TOUGH-M1/TOUGH-M1_negative.list'
  cluster_map: '~/graphpocket/cluster_map.pkl'
  result_dir: '~/graphpocket/results'

graph:
  threshold_k: 6
  algorithm: 'kd-tree'

##model config

model:
  input_scalar_size: 4
  output_scalar_size: 48
  edge_feat_size: 1
  vector_size: 16
  n_message_gvps: 1
  n_update_gvps: 1
  n_convs: 2
  dropout: 0.2
  message_norm: 0
  vector_gating: true
  xavier_init: true

loss:
  margin: 1.0
  stab_loss : 0.05

##train config and hyperparameters

train:
  n_epochs: 30
  batch_size: 128
  n_workers: 6

  optimizer:
    type: 'Adam'
    lr: 0.005
    weight_decay: 0.00000001
  
  scheduler:
    type: "StepLR"
    params:
      step_size: 5
      gamma: 0.5
    
    # - type: 'ReduceLROnPlateau
    #   params: 
    #     factor: 0.1
    #     patience: 10
    #     threshold: 0.001
    #     threshold_type: 'abs'
      
#wandb sweep args: dropout, margin, lr, weight_decay, step_size, gamma, n_convs
